### Variables
@baseUrl = http://localhost:8081
@directUrl = http://localhost:8080

POST {{baseUrl}}/api/v1/auth/signup
Content-Type: application/json


{
  "email": "swanhtetaungp@gmail.com",
  "password": "StrongPassword123!",
  "phone": "+1234567890",
  "name": "Swan Htet"
}
