# .air.toml - Hot reload configuration for auth-service
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []

bin = "./tmp/auth-service"

cmd = "go build -o ./tmp/auth-service ./cmd"

delay = 1000

exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  "testdata",
  "logs",
  "docs",
  "api",
  ".git",
  "bin"
]

# Files to exclude
exclude_file = [
  ".gitignore",
  ".env",
  "README.md",
  "Dockerfile",
  "Makefile",
  ".air.toml"
]

# Regex patterns to exclude
exclude_regex = [
  "_test\\.go$",
  "\\.log$",
  "\\.tmp$",
  "\\.swp$",
  "\\.DS_Store$"
]

exclude_unchanged = false
follow_symlink = false
full_bin = ""

# Directories to include (empty means all)
include_dir = [
  "cmd",
  "internal",
  "pkg"
]

# File extensions to watch
include_ext = [
  "go",
  "tpl",
  "tmpl",
  "html",
  "yml",
  "yaml",
  "json",
  "graphql"
]

# Specific files to include
include_file = []

# Kill delay
kill_delay = "1s"

# Build error log
log = "tmp/build-errors.log"

# Polling settings
poll = false
poll_interval = 0

# Pre/post commands
pre_cmd = ["echo 'Building auth-service...'"]
post_cmd = ["echo 'Build completed!'"]

# Rerun settings
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = true

[color]
app = "blue"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = true

[proxy]
enabled = false
app_port = 8080
proxy_port = 8081

[screen]
clear_on_rebuild = true
keep_scroll = false