name: workflow.yml

on:
  push:
    branches: [main]
    paths:
      - 'services/auth-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'services/auth-service/**'
  workflow_dispatch:

jobs:
  flow:
    name: 'Run unit tests and build/push Docker image'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/auth-service

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests recursively
        run: go test -v ./...

      - name: Build the docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service-cms:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service-cms:latest