name: workflow.yml
on:
  push:
    branches: [main]
    paths:
      - 'services/auth-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'services/auth-service/**'
  workflow_dispatch:

jobs:
  flow:
    name: 'Running the unit test and work flow'
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: Set up
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - name: Downloading the dependency
      run: go mod download
      working-directory: 'services/auth-service'

    - name: 🧪 Run unit tests recursively
      run: go test -v ./...

    - name: Building the docker container
      run: docker build -t auth-service .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD}}

    - name: Build the docker image
      run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/auth-service-cms:latest .

    - name: Pushing the image to Hub
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/auth-service-cms:latest


